package one.digitalinnovation.heroesapi.document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Heroes_Table")
public class Heroes {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "universe")
    private String universe;

    @DynamoDBAttribute(attributeName = "films")
    private int films;

    @Deprecated
    public Heroes() {}

    public Heroes(String id, String name, String universe, int films) {
        this.id = id;
        this.name = name;
        this.universe = universe;
        this.films = films;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUniverse() {
        return universe;
    }

    public void setUniverse(String universe) {
        this.universe = universe;
    }

    public int getFilms() {
        return films;
    }

    public void setFilms(int films) {
        this.films = films;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Heroes)) return false;

        Heroes heroes = (Heroes) o;

        if (getFilms() != heroes.getFilms()) return false;
        if (getId() != null ? !getId().equals(heroes.getId()) : heroes.getId() != null) return false;
        if (getName() != null ? !getName().equals(heroes.getName()) : heroes.getName() != null) return false;
        return getUniverse() != null ? getUniverse().equals(heroes.getUniverse()) : heroes.getUniverse() == null;
    }

    @Override
    public int hashCode() {
        int result = getId() != null ? getId().hashCode() : 0;
        result = 31 * result + (getName() != null ? getName().hashCode() : 0);
        result = 31 * result + (getUniverse() != null ? getUniverse().hashCode() : 0);
        result = 31 * result + getFilms();
        return result;
    }

    @Override
    public String toString() {
        return "Heroes{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", universe='" + universe + '\'' +
                ", films=" + films +
                '}';
    }
}
